+incdir+./src

./src/d_latch.v
./src/d_flipflop.v
./src/mux_2to1.v
./src/mux_4to1.v
./src/mux_8to1.v
./src/register_8.v
./src/full_adder.v
./src/ripple_adder_4.v
./src/ripple_adder_8.v
./src/adder_subtractor.v
./src/shifter_8.v
./src/multiplier_4.v
./src/alu.v
src/decode_memory.v
src/decode_arithmetic.v
src/decode_unary.v
src/decode_jump.v
src/instruction_decoder.v
src/sequencer.v
src/register_4.v
src/flag_register.v
src/program_counter.v
src/decode_system.v
src/instruction_sequencer.v
src/interrupt_sequencer.v
src/cpu.v
src/toplevel.v
