program = { whitespace | statement } , EOF ;

whitespace = " " | "\n" | "\t" | comment ;
comment = ";" , { ? any character except newline ? } ;

statement = const_decl
		  | label_decl
          | directive
          | instruction ;

const_decl = identifier , "=" , number ;

label_decl = identifier , ":" ;

(* case-insensitive *)
directive = org_directive
          | byte_directive
          | word_directive
          | dword_directive ;

(* case-insensitive *)
org_directive = ".ORG" , number ;          (* e.g. .ORG $8c00 *)
byte_directive = ".BYTE" , data_list ;     (* e.g. .BYTE $55, "Hello", 0 *)
word_directive = ".WORD" , number_list ;   (* e.g. .WORD $aa55 *)
dword_directive = ".DWORD" , number_list ; (* e.g. .DWORD $12345678 *)

data_list = (number | string) , { "," , ( number | string ) } ;
number_list = number , { "," , number } ;

string = '"' , { string_char } , '"' ;
string_char = ? any ASCII except `"` and `\` ?
            | escape_sequence ;

instruction = mnemonic , [ operand ] ;

(* case-insensitive *)
mnemonic = "ADC" | "AND" | "BCC" | "BCS"
         | "BEQ" | "BMI" | "BNE" | "BPL"
         | "BRA" | "BVC" | "BVS" | "CLC"
         | "CLV" | "CMP" | "DEC" | "DEX"
         | "DEY" | "HLT" | "INC" | "INX"
         | "INY" | "JMP" | "LD"  | "LDI"
         | "LDX" | "LDY" | "MUL" | "NOP"
         | "NOT" | "OR"  | "ROL" | "ROR"
         | "SEC" | "SEV" | "ST"  | "STX"
         | "STY" | "SBC" | "SHL" | "SHR"
         | "TAX" | "TAY" | "TXA" | "TXY"
         | "TYA" | "TYX" | "XOR" ;

operand = operand_imp
		| operand_ind
		| operand_imm
		| operand_abs
		| operand_ref ;

operand_imp = "IX" | "IY" ;      (* e.g. "ADC IX", case-insensitive *)
operand_ind = "[" , "IY" , "]" ; (* e.g. "[IY]", case-insensitive *)
operand_imm = "#" , constant ;   (* e.g. "#$0a" *)
operand_abs = constant ;         (* Literal address or offset *)
operand_ref = label ;            (* ":label" -> ABS or REL, semantics should handle it  *)

constant = number | identifier ;

label = ":" , identifier ;

identifier = letter , { letter | digit | "_" } ; (* case-sensitive *)

letter = "A" | ... | "Z" | "a" | ... | "z" ;

number = character | ( [ "+" | "-" ] , ( dec | hex | bin) );

dec = digit , { digit | "_" } ;
hex = "$" , hexdigit , { hexdigit | "_" } ;
bin = "%" , bindigit , { bindigit | "_" } ;

character = "'" , char_char , "'" ;
char_char = ? any ASCII except `'` and `\` ?
          | escape_sequence ;

escape_sequence = "\\" , ( "n" | "t" | "r" | "\\" | "\"" | "\'" | "\0" | ( "x" , hexdigit , hexdigit ) ) ;

digit = "0" | ... | "9" ;

hexdigit = "0" | ... | "9" | "a" | ... | "f" ;

bindigit = "0" | "1" ;
