program = { whitespace | statement } , EOF ;

whitespace = " " | "\n" | "\t" | comment ;
comment = ";" , { ? any character except newline ? } ;

statement = comment
          | label_decl
          | directive
          | instruction ;

label_decl = identifier , ":" ;

directive = org_directive
          | byte_directive
          | word_directive
          | text_directive ;

(* case-insensitive *)
org_directive = ".ORG" , operand_abs ;   (* e.g. .ORG $8c00 *)
byte_directive = ".BYTE" , number_list ; (* e.g. .BYTE $55 *)
word_directive = ".WORD" , number_list ; (* e.g. .WORD $aa55 *)
text_directive = ".TEXT" , text_list ;   (* .TEXT "Hello", $0a, "world", 0 *)

number_list = number , { "," , number } ;
text_list = string , { "," , ( string | number ) } ;

string = '"' , { ASCII } , '"' ;

ASCII  = ? any 8-bit character except `"` and newline ? ;

instruction = mnemonic , [ operand ] ;

(* case-insensitive *)
mnemonic = "ADC" | "AND" | "BCC" | "BCS"
         | "BEQ" | "BMI" | "BNE" | "BPL"
         | "BRA" | "BVC" | "BVS" | "CLC"
         | "CLV" | "CMP" | "DEC" | "DEX"
         | "DEY" | "HLT" | "INC" | "INX"
         | "INY" | "JMP" | "LD"  | "LDI"
         | "LDX" | "LDY" | "MUL" | "NOP"
         | "NOT" | "OR"  | "ROL" | "ROR"
         | "SEC" | "SEV" | "ST"  | "STX"
         | "STY" | "SBC" | "SHL" | "SHR"
         | "TAX" | "TAY" | "TXA" | "TXY"
         | "TYA" | "TYX" | "XOR" ;

operand = operand_imp
		| operand_ind
		| operand_imm
		| operand_abs
		| operand_ref ;

operand_imp = "IX" | "IY" ;      (* e.g. "ADC IX", case-insensitive *)
operand_ind = "[" , "IY" , "]" ; (* e.g. "[IY]", case-insensitive *)
operand_imm = "#" , number ;     (* e.g. "#$0a" *)
operand_abs = number ;           (* Literal address or offset *)
operand_ref = label ;            (* ":label" -> ABS or REL, semantics should handle it  *)

label = ":" , identifier ;

identifier = letter , { letter | digit | "_" } ; (* case-sensitive *)

letter = "A" | ... | "Z" | "a" | ... | "z" ;

number = [ "+" | "-" ] , ( dec | hex | bin ) ;

dec = digit , { digit | "_" } ;
hex = "$" , hexdigit , { hexdigit | "_" } ;
bin = "%" , bindigit , { bindigit | "_" } ;

hexdigit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7"
		| "8" | "9" | "a" | "b" | "c" | "d" | "e" | "f" ;

bindigit = "0" | "1" ;
